### ISSUE TITLE
1.4.1 serverselector.desktop doesn't open the server selector

### ISSUE THREAD

**Issue by mustafhadin** [MishaProductions/EpinelPS#16]
I have tried it from multiple file locations (launcher folder, standalone separate from the game directories, etc). It pops up with the admin warning, but the server window itself never shows. I've also tried the 1.4 branch, same issue.

**Comment by MishaProductions** [comment]
Is .NET Desktop Runtime 8.0.8 installed?

**Comment by mustafhadin** [comment]
It is, yeah. Tried reinstalling it, too.

**Comment by MishaProductions** [comment]
Can you check the windows event viewer?

**Comment by mustafhadin** [comment]
![image](https://github.com/user-attachments/assets/e76bca5c-a56e-4d56-b60b-6ccbdf0264c5)
![image](https://github.com/user-attachments/assets/91ded7cc-94c2-4e01-9b9e-50fe0f7bf78a)
sorry for taking so long to reply, was out of town

**Comment by MishaProductions** [comment]
Doesn't seem to be related to my code, could be related to .NET or Avalonia. Can you please compile and run the project and see if that shows any exceptions in the Visual Studio debugger? Not sure how to debug this issue.

**Comment by NoahBox** [comment]
Same problem with me. Check event next to the one in your screenshot with EventId 1026 (.NET Runtime). Detailed error stack is included. In my case, due to improper operation before, my HOST file is unreadable thou elevated, so a FileNotFoundException is threw.
